version: '3.1'
services:

  db:
    image: postgres
    restart: unless-stopped
    env_file:
      - .env.docker
    ports:
      - "5432:5432"
    container_name: eod.db
      
  node:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    image: node:16
    env_file:
      - .env.docker
    ports:
      - "3000:3000"
    container_name: eod.node
    command: bash -c 'npx prisma migrate dev --name init && npm run docker-start'
    depends_on:
      - db
